//import { MAIN_PANEL_ROUTES } from './../main-panel/main-panel.routing';
//import { MainPanelComponent } from './../main-panel/main-panel.component';
import { Routes } from "@angular/router";
import { IngredientsdetailsComponent } from "./../ingredientsdetails/ingredientsdetails.component";
import { NewingredientComponent } from "./../newingredient/newingredient.component";
import { RecipedetailsComponent } from "./../recipedetails/recipedetails.component";
import { NewrecipeComponent } from "./../newrecipe/newrecipe.component";
import { ProductdetailsComponent } from "./../productdetails/productdetails.component";
import { NewproductComponent } from "./../newproduct/newproduct.component";
import { ProductspopupComponent } from "./../productspopup/productspopup.component";
import { IngredientsComponent } from "./../ingredients/ingredients.component";
import { RecipeComponent } from "./../recipe/recipe.component";
import { ProductsComponent } from "./../products/products.component";
import { HomeComponent } from "./../home/home.component";
import { FastuserComponent } from "./../fastuser/fastuser.component";
import { OrderComponent } from "./../order/order.component";
import { PointsComponent } from "./../points/points.component";
import { PurchasesComponent } from "../purchases/purchases.component";
import { PromotionsComponent } from "../promotions/promotions.component";
import { UsersComponent } from "../users/users.component";
import { ReportsComponent } from "../reports/reports.component";
import { ConfigComponent } from "../config/config.component";
import { PromotionDetailsComponent } from "../promotion-details/promotion-details.component";
import { PurchaseDetailsComponent } from "../purchase-details/purchase-details.component";
import { NewPurchaseComponent } from "../new-purchase/new-purchase.component";
import { NewPromotionComponent } from "../new-promotion/new-promotion.component";
import { NewUserComponent } from "../new-user/new-user.component";
import { UserdetailsComponent } from "../userdetails/userdetails.component";
import { NewfeaturedComponent } from "../newfeatured/newfeatured.component";
import { FeaturedComponent } from "../featured/featured.component";

export const MAIN_ROUTING: Routes = [
  { path: '', redirectTo: "/dashboard", pathMatch: "full" },
  { path: 'dashboard', component: HomeComponent },
  { path: "points", component: PointsComponent },
  { path: "order", component: OrderComponent },
  { path: "fastuser", component: FastuserComponent },
  { path: "products", component: ProductsComponent },
  { path: "productspopup", component: ProductspopupComponent },
  { path: "newproduct", component: NewproductComponent },
  { path: "productdetails/:id", component: ProductdetailsComponent },
  { path: "recipe", component: RecipeComponent },
  { path: "newrecipe", component: NewrecipeComponent },
  { path: "recipedetails/:id", component: RecipedetailsComponent },
  { path: "ingredients", component: IngredientsComponent },
  { path: "newingredient", component: NewingredientComponent },
  { path: "ingredientdetails/:id", component: IngredientsdetailsComponent },
  { path: "newPurchase", component: NewPurchaseComponent },
  { path: "purchases", component: PurchasesComponent },
  { path: "purchaseDetails/:id", component: PurchaseDetailsComponent },
  { path: "newpromotion", component: NewPromotionComponent },
  { path: "promotions", component: PromotionsComponent },
  { path: "promotiondetails/:id", component: PromotionDetailsComponent },
  { path: "reports", component: ReportsComponent },
  { path: "users", component: UsersComponent },
  { path: "newuser", component: NewUserComponent },
  { path: "userdetails/:id", component: UserdetailsComponent },
  { path: "config", component: ConfigComponent },
  { path: "featured", component: FeaturedComponent },
  { path: "newfeatured", component: NewfeaturedComponent },  
];
